[*]
dedup-cache-models = true ;hide raw cache entries from GET /models in router mode
flash-attn = on ;needs to be on for kv quant to work
cache-type-k = q8_0
cache-type-v = q8_0
ctx-size = 131072
jinja = true
no-mmproj = true ;vision support eats around 1gb of vram so disable it
ctx-checkpoints = 12
temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.00
n-gpu-layers = all
n-gpu-layers-draft = all
spec-type = draft-mtp,ngram-mod
spec-draft-n-max = 3
spec-draft-backend-sampling = true
spec-draft-sampling = probabilistic
backend-sampling = true
reasoning-preserve = true

[Qwen3.6-35B-A3B-IQ4-MTP]
hf = unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-IQ4_XS
temp = 0.6

[Ornith-1.5-35B-A3B-IQ3_S]
hf = AtomicChat/Ornith-1.5-35B-A3B-GGUF:IQ3_S
temp = 0.6
spec-type = none

[Qwen3.8-27B-xhigh]
hf = unsloth/Qwen3.8-27B-GGUF:IQ4_XS
cache-type-v = q5_1

[Qwen3.8-27B-medium]
hf = unsloth/Qwen3.8-27B-GGUF:IQ4_XS
cache-type-v = q5_1
reasoning-effort = medium
;wait tokens bias based on https://www.reddit.com/r/LocalLLaMA/comments/1wromzr/adding_logit_penalty_for_wait_maybe_and_perhaps/
logit-bias = 466-2,694-2,1362-2,1412-2,1921-2,1990-2,2086-2,2361-2,2441-2,2493-2,2892-2,3222-2,3315-2,3384-2,3404-2,3482-2,3655-2,4213-2,4370-2,4598-2,4611-2,4808-2,5752-2,6970-2,7014-2,7643-2,8106-2,10179-2,10451-2,11746-2,13264-2,13428-2,14673-2,15029-2,16036-2,21143-2,21979-2,33955-2,35999-2,36563-2,37201-2,37781-2,41484-2,62586-2,66073-2,73071-2,84485-2,85152-2,95500-2

[Muse-Glimmer-30B-Q4-DFlash]
hf = unsloth/Muse-Glimmer-30B-GGUF:UD-Q4_K_XL
cache-type-k = f16
cache-type-v = f16
spec-type = draft-dflash
spec-draft-n-max = 15
spec-draft-p-min = 0.4
temp = 1.0
top-p = 0.95
top-k = 64

[Gemma4-31B-Q4-MTP]
ctx-size = 25000
hf = unsloth/gemma-4-31B-it-qat-GGUF:UD-Q4_K_XL
no-mmproj = false
temp = 1.0
top-p = 0.95
top-k = 64
min-p = 0.05

[Gemma4-26B-A4B-Q4-MTP]
hf = unsloth/gemma-4-26B-A4B-it-qat-GGUF:UD-Q4_K_XL
no-mmproj = false
temp = 1.0
top-p = 0.95
top-k = 64
min-p = 0.05

[Gemma4-12B-Q4-MTP]
hf = unsloth/gemma-4-12B-it-qat-GGUF:UD-Q4_K_XL
no-mmproj = false
temp = 1.0
top-p = 0.95
top-k = 64
min-p = 0.05

[Ling3-Tiny-Q6]
hf = bartowski/Ling-3.0-tiny-GGUF:Q6_K_L
temp = 1.0
top-p = 0.95
top-k = 20
spec-type = none
cache-type-k = f16
cache-type-v = f16